Repository canonical/summit.ubuntu.com, pull requests merged in 2022-09, with the labels that each got.

#9 Update page to include cfp section
  src/index.html
Labels: Review: QA +1, Review: Code +1 with changes

#12 add redirect to the events site
  nginx.conf
Labels: Review: Code +1, Review: QA +1

#11 Update port to 8048
  .env
  .github/workflows/pr.yaml
Labels: Review: Code +1
